### ISSUE TITLE
Move to async-hook

### ISSUE THREAD

**Issue by felixheck** [toboid/correlation-id#11]
Hey!

You mention in the README that you intend to move to async-hook when it's generally available.
Is node v8.0.0 still too early for "general availability"? :)

**Comment by toboid** [comment]
Hey, thanks for the nudge. No not too early, it would a good time to get started on this. Will leave this issue open and update when i've made some progress.

**Comment by felixheck** [comment]
@toboid thanks! Looking forward :)

**Comment by felixheck** [comment]
Maybe that existing repo could help:
https://github.com/musicglue/wrap-async-context/blob/master/lib/index.js

Additionally I started with a prototype:
https://github.com/felixheck/correlation-id

but it is not working yet..
especially the nested usage of bindId/withId

**Comment by ianbale** [comment]
Hi,

Just wondering how this is coming along?

I'm working on an app that uses async/await and could really use this.

So I am wondering when this is likely to be done...if it's not going to be ready in time I will have to look at other options. Our go live is a fair way off though.

**Comment by toboid** [comment]
Hi,

This module doesn't yet support async/await, i've added a note to the readme to make this clear. 

I haven't got round to moving to async hooks yet but intend to do so as soon as I get chance. However async hooks is still experimental in node 8 so i wouldn't trust an implementation based on that in production just yet. I'm not sure if async hooks will help with support for async/await in this module but I suspect so.

I'll be sure to update this issue as soon as there is something to show.

**Comment by ianbale** [comment]
Ah... ok. Thanks for the clarification.

This app is likely to go live around April next year, but will need to have undergone some serious testing before then. However, I was only hoping to use this module for logging event during the course of responding to a request - rather than have to pass request IDs around everywhere. But logging is not mission critical, so I'm not too concerned.

I really like the async/await syntax. A huge improvement over what we had before. Although it does have some serious limitations, so I'm using the old syntax in quite a few places too. 

Anyway, thanks for sharing this module. In those places where I am not using async/await it is working perfectly and is far easier to use than any of the alternatives I have tried.

**Comment by toboid** [comment]
Glad to hear that 😄 . I'll keep you posted on progress with this.

**Comment by twhitner-vistaprint** [comment]
I am also interested in async/await.  Have been happily using this package started the move to async/await before realizing this didn't support it...

**Comment by santi8ago8** [comment]
@felixheck Nice job with async hooks!!! Thanks 😄

**Comment by felixheck** [comment]
@santi8ago8 it's just a first step..doesn't work up to now :(

**Comment by toboid** [comment]
Apologies for the delay, adding support for async/await will be my priority now. I'll keep you up to date

**Comment by felixheck** [comment]
@toboid yeah, sounds great :)

**Comment by rubanour** [comment]
Hey, I tried to use the fork [cls-hooked](https://github.com/jeff-lewis/cls-hooked) that uses async_hooks for node versions >= 8.2.1. It works for me with node 9. 

I opened a PR here https://github.com/toboid/correlation-id/pull/19. Please feel free to check if it works for you and to point out any possible issues.

**Comment by toboid** [comment]
Thanks for the PR, it's working well. Still intending to move to async hooks but it's non trivial and just haven't had the time to give it the attention it needs. Would welcome a PR for that too. Leaving this issue open to track.

**Comment by toboid** [comment]
async/await support available in version @2.1.1

**Comment by CharlesKozel** [comment]
I noticed the readme.md still links to continuation-local-storage instead of cls-hooked

https://github.com/toboid/correlation-id#how-does-it-work

**Comment by toboid** [comment]
Thanks, updated

**Comment by toboid** [comment]
V4 of this library is now released which uses [AsyncLocalStorage](https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage) from Node Async hooks, there's full support for async/await and no need for an external dependency to track the correlation id.
