### ISSUE TITLE
Will this module cost memory over time?

### ISSUE THREAD

**Issue by charandas** [toboid/correlation-id#3]
How often can `withId()` be called without significantly affecting application memory usage?

Mostly, I mean to ask if the underlying mechanism allows for some sort of garbage collection?

**Comment by charandas** [comment]
Seems like it won't. The memory should be reclaimed as functions return. I am no expert on this though, so thought I will ask.

**Comment by toboid** [comment]
Hi, yes memory should be reclaimed automatically when out of scope.

Any impact on memory usage will depend on your specific app, concurrency and usage etc. Best advice is to do a performance test of your app and see.

**Comment by charandas** [comment]
Thanks @toboid.
