### ISSUE TITLE
Make req.user.id available?

### ISSUE THREAD

**Issue by olemartin** [toboid/correlation-id#32]
Would be great to have other data available through this library. For instance `req.user.id`. Could you consider adding it?

**Comment by toboid** [comment]
Hey, thanks for your interest. This module has quite a specific scope so I don't think that would fit. 

Have you looked at https://github.com/Jeff-Lewis/cls-hooked?  That's a more generic way of keeping hold of some data across async calls that I think could satisfy your use case very well.

Hope this is useful 🙂
